config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'dashboards#index', as: :authenticated_root
    end

    # Go to login page if not yet logged in
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :clothes_sizes, only: [:index, :create, :update]
  resources :customers, only: [:index, :create]
  resources :design_service_price_lists, only: [:index, :show, :create, :update]
  resources :garments, only: [:index]
  resources :registrations, only: [:new, :create]
  resources :sales, only: [:index, :create]
end

app/views/layouts/_menu.html.erb
<!-- Dropdown menu structure for Accounts -->
<ul id="account-dropdown-menu" class="dropdown-content">
  <li><a href="#">Change Password</a></li>
  <li class="divider"></li>
  <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
</ul>

<nav>
  <div class="nav-wrapper">
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to 'Sales', sales_path %></li>
      <li><%= link_to 'Service Price List', design_service_price_lists_path %></li>
      <li><%= link_to 'Clothes Sizes', clothes_sizes_path %></li>
      <li><%= link_to 'Customers', customers_path %></li>

      <% if current_user.role == Role.admin %>
        <li><%= link_to 'Add Member', new_registration_path %></li>
      <% end %>

      <li><a class="dropdown-button" href="javascript:void(0);" data-activates="account-dropdown-menu">Account<i class="material-icons right">person</i></a></li>
    </ul>
    <a href="#" class="brand-logo left">Logo</a>
  </div>
</nav>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    'use strict';

    $('.dropdown-button').dropdown();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Accountancy</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.14/moment-timezone.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield :modals %>

    <% if user_signed_in? %>
      <%= render 'layouts/menu' %>
    <% end %>

    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <div class="container">
      <%= yield %>
    </div>

    <script type="text/javascript" charset="utf-8">
      // Re-initialize waves effect on MaterializeCSS
      Waves.displayEffect();
    </script>
  </body>
</html>